config/routes.rb
GremioVirtual::Application.routes.draw do

  devise_for :usuarios,
          path: "",
          controllers: { 
                    sessions: "usuarios/sessions",
                    registrations: "usuarios/registrations",
                    passwords: "usuarios/passwords",
                    password_expired: "usuarios/password_expired"
                  },
                  path_names: { 
                    sign_in: 'entrar',
                    sign_out: 'sair',
                    password: 'senha', 
                    confirmation: 'confirmacao', 
                    unlock: 'desbloquear', 
                    registration: 'perfil', 
                    sign_up: 'sign_up',
                    password_expired: 'senha_expirou'
                }
  
  resources :colegios
  resources :funcionarios
  resources :turmas
  resources :alunos
  
  resources :representante_de_turmas
  
  resources :turmas do
    resources :alunos
    resources :representante_de_turmas, :as => 'representantes', :path => 'representantes'
  end
  
  resources :assembleia_gerais
  
  resources :gremios
  
  resources :chapas
  resources :membro_chapas
  resources :chapas do
    resources :membro_chapas, :as => 'membros'
    collection do
      get 'finalizar_cadastro', :path => '/:id/finalizar_cadastro'
      post 'votar',             :path => '/:id/votar'
    end
  end
  
  resources :eleicao_gremios do
    collection do
      get 'votacao', :path => '/:id/votacao'
    end
  end
  
  resources :cargo_representante_de_turmas
  resources :cargo_funcionarios
  resources :cargo_membro_comissao_eleitorais
  resources :cargo_membro_conselho_fiscais
  
  resources :conselho_fiscais
  resources :conselho_fiscais do
    resources :membro_conselho_fiscais, :as => 'membros', :path => 'membros'
    collection do
      get 'finalizar_cadastro',        :path => '/:id/finalizar_cadastro'
      get 'adicionar_membro_efetivo',  :path => '/:id/adicionar_membro_efetivo/:membro_id'
      get 'adicionar_membro_suplente', :path => '/:id/adicionar_membro_suplente/:membro_id'
    end
  end
  
  resources :conselho_representantes_de_turmas
  resources :conselho_representantes_de_turmas do
    resources :representante_de_turmas, :as => 'representantes', :path => 'representantes'
  end
  
  resources :membro_conselho_fiscais
  resources :comissao_eleitorais do
    resources :membro_comissao_eleitorais, :as => 'membros', :path => 'membros'
    resources :modelo_estatutos
  end
  
  resources :gremios do
    resources :socio_gremios, :as => 'socios', :path => 'socios'
    resources :comissao_eleitorais
    resources :assembleia_gerais
    resources :conselho_representantes_de_turmas
    resources :conselho_fiscais
  end
      
  resources :conselho_fiscais
  resources :conselho_fiscais, :as => :conselho_fiscal do
    resources :membro_conselho_fiscais, :as => 'membros', :path => 'membros'
    collection do
      get 'adicionar_membro_efetivo', :path => '/:conselho_fiscal_id/adicionar_membro_efetivo/:membro_id'
      get 'adicionar_membro_suplente', :path => '/:conselho_fiscal_id/adicionar_membro_suplente/:membro_id'
    end
  end
  
  resources :comissao_pro_gremios
  resources :comissao_pro_gremios do
    resources :membro_comissao_pro_gremios, :as => 'membros', :path => 'membros'
    collection do
      get 'finalizar_cadastro', :path => '/:id/finalizar_cadastro'
      get 'adicionar_membro', :path => '/:id/adicionar_membro/:aluno_id'
    end
  end
  resources :membro_comissao_pro_gremios
  
  
  resources :comissao_eleitorais
  resources :comissao_eleitorais do
    collection do
      get 'finalizar_cadastro', :path => '/:id/finalizar_cadastro'
      get 'adicionar_membro', :path => '/:id/adicionar_membro/:aluno_id'
    end
  end
  
  resources :membro_comissao_eleitorais
  
  
  get 'gremio-estudantil-acoes' => 'gremio_info#acoes', :as => :gremio_estudantil_acoes
  get 'gremio-estudantil-organize-o-na-sua-escola' => 'gremio_info#organize_na_sua_escola', :as => :gremio_estudantil_organize_na_sua_escola
  get 'gremio-estudantil-como-organizar' => 'gremio_info#como_organizar', :as => :gremio_estudantil_como_organizar
  
  root 'gremio_info#acoes'

  
  

end

app/models/modelo_estatuto.rb
class ModeloEstatuto < ActiveRecord::Base
  belongs_to :comissao_pro_gremio, inverse_of: :modelo_estatuto
  
end

app/controllers/modelo_estatutos_controller.rb
class ModeloEstatutosController < ApplicationController
  before_action :set_modelo_estatuto, only: [:show, :edit, :update, :destroy]

  def index
    @modelo_estatutos = ModeloEstatuto.all
    respond_with(@modelo_estatutos)
  end

  def show
    respond_with(@modelo_estatuto)
  end

  def new
    @modelo_estatuto = ModeloEstatuto.new
    respond_with(@modelo_estatuto)
  end

  def edit
  end

  def create
    @modelo_estatuto = ModeloEstatuto.new(modelo_estatuto_params)
    @modelo_estatuto.save
    respond_with(@modelo_estatuto)
  end

  def update
    @modelo_estatuto.update(modelo_estatuto_params)
    respond_with(@modelo_estatuto)
  end

  def destroy
    @modelo_estatuto.destroy
    respond_with(@modelo_estatuto)
  end

  private
    def set_modelo_estatuto
      @modelo_estatuto = ModeloEstatuto.find(params[:id])
    end

    def modelo_estatuto_params
      params.require(:modelo_estatuto).permit(:comissao_pro_gremio_id, :aprovado, :estatuto)
    end
end

app/helpers/modelo_estatutos_helper.rb
module ModeloEstatutosHelper
end

app/views/modelo_estatutos/_form.html.erb
<%= form_for(@modelo_estatuto) do |f| %>
  <% if @modelo_estatuto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@modelo_estatuto.errors.count, "error") %> prohibited this modelo_estatuto from being saved:</h2>

      <ul>
      <% @modelo_estatuto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comissao_pro_gremio_id %><br>
    <%= f.text_field :comissao_pro_gremio_id %>
  </div>
  <div class="field">
    <%= f.label :aprovado %><br>
    <%= f.check_box :aprovado %>
  </div>
  <div class="field">
    <%= f.label :estatuto %><br>
    <%= f.text_area :estatuto %>
  </div>
  
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/modelo_estatutos/edit.html.erb
<div class="box-info full" >
	<div class="panel">
		<div class="panel-heading">
			<h2><strong> Editando Modelo de Estatuto </strong></h2>
		</div>
		
		<div class="panel-body">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/modelo_estatutos/index.html.erb
<h1>Listing modelo_estatutos</h1>

<table>
  <thead>
    <tr>
      <th>Comissao pro gremio</th>
      <th>Aprovado</th>
      <th>Estatuto</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @modelo_estatutos.each do |modelo_estatuto| %>
      <tr>
        <td><%= modelo_estatuto.comissao_pro_gremio %></td>
        <td><%= modelo_estatuto.aprovado %></td>
        <td><%= modelo_estatuto.estatuto %></td>
        <td><%= link_to 'Show', modelo_estatuto %></td>
        <td><%= link_to 'Edit', edit_modelo_estatuto_path(modelo_estatuto) %></td>
        <td><%= link_to 'Destroy', modelo_estatuto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Modelo estatuto', new_modelo_estatuto_path %>

app/views/modelo_estatutos/new.html.erb
<div class="box-info full" >
	<div class="panel">
		<div class="panel-heading">
			<h2><strong> Cadastrando Modelo de Estatuto </strong></h2>
		</div>
		
		<div class="panel-body">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/modelo_estatutos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comissao pro gremio:</strong>
  <%= @modelo_estatuto.comissao_pro_gremio %>
</p>

<p>
  <strong>Aprovado:</strong>
  <%= @modelo_estatuto.aprovado %>
</p>

<p>
  <strong>Estatuto:</strong>
  <%= @modelo_estatuto.estatuto %>
</p>

<%= link_to 'Edit', edit_modelo_estatuto_path(@modelo_estatuto) %> |
<%= link_to 'Back', modelo_estatutos_path %>