config/routes.rb
GremioVirtual::Application.routes.draw do

  devise_for :usuarios,
          path: "",
          controllers: { 
                    sessions: "usuarios/sessions",
                    registrations: "usuarios/registrations",
                    passwords: "usuarios/passwords",
                    password_expired: "usuarios/password_expired"
                  },
                  path_names: { 
                    sign_in: 'entrar',
                    sign_out: 'sair',
                    password: 'senha', 
                    confirmation: 'confirmacao', 
                    unlock: 'desbloquear', 
                    registration: 'perfil', 
                    sign_up: 'sign_up',
                    password_expired: 'senha_expirou'
                }
  
  resources :colegios
  resources :funcionarios
  resources :turmas
  resources :alunos
  
  resources :representante_de_turmas
  
  resources :turmas do
    resources :alunos
    resources :representante_de_turmas, :as => 'representantes', :path => 'representantes'
  end
  
  resources :assembleia_gerais
  
  resources :gremios
  
  resources :chapas
  resources :membro_chapas
  resources :chapas do
    resources :membro_chapas, :as => 'membros'
    collection do
      get 'finalizar_cadastro', :path => '/:id/finalizar_cadastro'
      post 'votar',             :path => '/:id/votar'
    end
  end
  
  resources :eleicao_gremios do
    collection do
      get 'votacao', :path => '/:id/votacao'
    end
  end
  
  resources :cargo_representante_de_turmas
  resources :cargo_funcionarios
  resources :cargo_membro_comissao_eleitorais
  resources :cargo_membro_conselho_fiscais
  
  resources :conselho_fiscais
  resources :conselho_fiscais do
    resources :membro_conselho_fiscais, :as => 'membros', :path => 'membros'
    collection do
      get 'finalizar_cadastro',        :path => '/:id/finalizar_cadastro'
      get 'adicionar_membro_efetivo',  :path => '/:id/adicionar_membro_efetivo/:membro_id'
      get 'adicionar_membro_suplente', :path => '/:id/adicionar_membro_suplente/:membro_id'
    end
  end
  
  resources :conselho_representantes_de_turmas
  resources :conselho_representantes_de_turmas do
    resources :representante_de_turmas, :as => 'representantes', :path => 'representantes'
  end
  
  resources :membro_conselho_fiscais
  resources :comissao_eleitorais do
    resources :membro_comissao_eleitorais, :as => 'membros', :path => 'membros'
    resources :modelo_estatutos
  end
  
  resources :gremios do
    resources :socio_gremios, :as => 'socios', :path => 'socios'
    resources :comissao_eleitorais
    resources :assembleia_gerais
    resources :conselho_representantes_de_turmas
    resources :conselho_fiscais
  end
      
  resources :conselho_fiscais
  resources :conselho_fiscais, :as => :conselho_fiscal do
    resources :membro_conselho_fiscais, :as => 'membros', :path => 'membros'
    collection do
      get 'adicionar_membro_efetivo', :path => '/:conselho_fiscal_id/adicionar_membro_efetivo/:membro_id'
      get 'adicionar_membro_suplente', :path => '/:conselho_fiscal_id/adicionar_membro_suplente/:membro_id'
    end
  end
  
  resources :comissao_pro_gremios
  resources :comissao_pro_gremios do
    resources :membro_comissao_pro_gremios, :as => 'membros', :path => 'membros'
    collection do
      get 'finalizar_cadastro', :path => '/:id/finalizar_cadastro'
      get 'adicionar_membro', :path => '/:id/adicionar_membro/:aluno_id'
    end
  end
  resources :membro_comissao_pro_gremios
  
  
  resources :comissao_eleitorais
  resources :comissao_eleitorais do
    collection do
      get 'finalizar_cadastro', :path => '/:id/finalizar_cadastro'
      get 'adicionar_membro', :path => '/:id/adicionar_membro/:aluno_id'
    end
  end
  
  resources :membro_comissao_eleitorais
  
  
  get 'gremio-estudantil-acoes' => 'gremio_info#acoes', :as => :gremio_estudantil_acoes
  get 'gremio-estudantil-organize-o-na-sua-escola' => 'gremio_info#organize_na_sua_escola', :as => :gremio_estudantil_organize_na_sua_escola
  get 'gremio-estudantil-como-organizar' => 'gremio_info#como_organizar', :as => :gremio_estudantil_como_organizar
  
  root 'gremio_info#acoes'

  
  

end

app/controllers/conselho_fiscais_controller.rb
# encoding: utf-8

class ConselhoFiscaisController < ApplicationController
  before_action :set_conselho_fiscal, only: [:show, :destroy, :finalizar_cadastro, :adicionar_membro_efetivo, :adicionar_membro_suplente]
  before_action :set_membro_efetivo, only: :adicionar_membro_efetivo
  before_action :set_membro_suplente, only: :adicionar_membro_suplente
  
  respond_to :html, :xml, :json
  
  
  def index
    if current_colegio.gremio
      redirect_to current_colegio.gremio.conselho_fiscal || new_conselho_fiscal_path
    else
      redirect_to new_gremio_path
    end
  end
  
  def show
    authorize @conselho_fiscal
    
    @alunos_efetivo = current_colegio.alunos
    @alunos_suplente = current_colegio.alunos
    
    respond_with @conselho_fiscal
  end
  
  def new
    @conselho_fiscal = ConselhoFiscal.new
    authorize @conselho_fiscal
    respond_with @conselho_fiscal
  end
  
  def create
    @conselho_fiscal = ConselhoFiscal.new(conselho_fiscal_params)
    @conselho_fiscal.ano_vigencia = Time.now.year
    @conselho_fiscal.gremio = current_colegio.gremio
    authorize @conselho_fiscal
    
    if @conselho_fiscal.save
      current_colegio.gremio.reload
      flash[:info] = "Conselho Fiscal salvo com sucesso"
    else
      flash[:warning] = "Não foi possível salvar os dados do Conselho Fiscal"
    end
    
    respond_with @conselho_fiscal
  end
  
  def finalizar_cadastro
    @conselho_fiscal.finalizado = true
    
    if @conselho_fiscal.save
      flash[:info] = "Conselho Fiscal finalizado"
    else
      flash[:warning] = "Não foi possível salvar o Conselho Fiscal"
    end
    
    redirect_to @conselho_fiscal
  end
  
  def adicionar_membro_efetivo
    @conselho_fiscal.membros << @membro_efetivo
    
    if @conselho_fiscal.save
      flash[:info] = "Membro Efetivo adicionado com sucesso"
    else
      flash[:warning] = "Não foi possível adicionar este membro"
    end
    
    redirect_to @conselho_fiscal
  end
  
  def adicionar_membro_suplente
    @conselho_fiscal.membros << @membro_suplente
    
    if @conselho_fiscal.save
      flash[:info] = "Membro Suplente adicionado com sucesso"
    else
      flash[:warning] = "Não foi possível adicionar este membro"
    end
    
    redirect_to @conselho_fiscal
  end
  
  
  def destroy
    authorize @conselho_fiscal
    @conselho_fiscal.destroy
    respond_with @conselho_fiscal
  end
  
  private
    def set_conselho_fiscal
      @conselho_fiscal = ConselhoFiscal.find(params[:id])
    end
    
    def conselho_fiscal_params
      params.require(:conselho_fiscal).permit(:gremio_id)
    end
    
    def membro_params
      params.permit(:aluno_id, :cargo_membro_conselho_fiscal_id)
    end
    
    def set_membro_efetivo
      @membro_efetivo = MembroConselhoFiscal.new(membro_params)
      @membro_efetivo.efetivo = true
    end
    
    def set_membro_suplente
      @membro_suplente = MembroConselhoFiscal.new(membro_params)
      @membro_suplente.suplente = true
    end
end

app/helpers/conselho_fiscais_helper.rb
module ConselhoFiscaisHelper
end

app/views/conselho_fiscais/_form.html.erb
<%= form_for(@conselho_fiscal) do |f| %>
	<% if @conselho_fiscal.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@conselho_fiscal.errors.count, "erro") %> </h2>
		
			<ul>
				<% @conselho_fiscal.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<%= f.hidden_field :gremio_id, :value => current_colegio.gremio.id %>
	
	<% if policy(:conselho_fiscal).new? %>
		<%= f.submit :class => 'btn btn-primary' %>
	<% end %>
<% end %>

app/views/conselho_fiscais/_modal_consulta_alunos_membro_efetivo.html.erb
<style>
	div#consulta-alunos-modal {
		max-width: 800px;
		width: 90%;
		height: 75%;
		overflow: auto;
	}
</style>

<div class="md-modal md-slide-in-right" id="consulta-alunos-modal">
	<div class="box-info modal-content">
		<h2 class="text-center"> 
			<strong> Alunos (Membro Efetivo)</strong> 
			<button class="btn btn-default btn-xs md-close pull-right"> <strong>X</strong> Fechar </button>
		</h2>
		<div>
			<div class="form-group">
				<% if @alunos_efetivo.count > 0 %>
					<table class="table table-responsive table-condensed" id="alunos">
						<thead class="my-table-header">
							<th> Matrícula </th>
							<th style="width: 4cm"> Aluno </th>
							<th> Série </th>
							<th></th>
						</thead>
						<tbody>
							<% @alunos_efetivo.each do |a| %>
								<tr>
									<td> <%= a.matricula %> </td>
									<td> <%= a.nome %> </td>
									<td> <%= a.turma.nome %> </td>
									<td class="text-left"> <a id="add-membro" href="<%= adicionar_membro_efetivo_conselho_fiscais_path(@conselho_fiscal, a) %>"> <i class="fa fa-plus"></i> </a> </td>
								</tr>
							<% end %>
						</tbody>
					</table>
				<% else %>
					<h5> Nenhum aluno disponível... </h5>
				<% end %>
			</div>
		</div>
	</div>
</div>
<div class="md-overlay"></div>

app/views/conselho_fiscais/_modal_consulta_alunos_membro_suplente.html.erb
<style>
	div#consulta-alunos-modal {
		max-width: 800px;
		width: 90%;
		height: 75%;
		overflow: auto;
	}
</style>

<div class="md-modal md-slide-in-right" id="consulta-alunos-modal">
	<div class="box-info modal-content">
		<h2 class="text-center"> 
			<strong> Alunos (Membro Suplente) </strong> 
			<button class="btn btn-default btn-xs md-close pull-right"> <strong>X</strong> Fechar </button>
		</h2>
		<div>
			<div class="form-group">
				<% if @alunos_suplente.count > 0 %>
					<table class="table table-responsive table-condensed" id="alunos">
						<thead class="my-table-header">
							<th> Matrícula </th>
							<th style="width: 4cm"> Aluno </th>
							<th> Série </th>
							<th></th>
						</thead>
						<tbody>
							<% @alunos_suplente.each do |a| %>
								<tr>
									<td> <%= a.matricula %> </td>
									<td> <%= a.nome %> </td>
									<td> <%= a.turma.nome %> </td>
									<td class="text-left"> <a id="add-membro" href="<%= adicionar_membro_efetivo_conselho_fiscais_path(@conselho_fiscal, a) %>"> <i class="fa fa-plus"></i> </a> </td>
								</tr>
							<% end %>
						</tbody>
					</table>
				<% else %>
					<h5> Nenhum aluno disponível... </h5>
				<% end %>
			</div>
		</div>
	</div>
</div>
<div class="md-overlay"></div>

app/views/conselho_fiscais/edit.html.erb
<div class="box-info full" >
	<div class="panel">
		<div class="panel-heading">
			<h2 class="text-center">
				<strong> Editando Conselho Fiscal </strong>
			</h2>
			
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/conselho_fiscais/index.html.erb
<h1>Listing conselho_fiscais</h1>

<table>
  <thead>
    <tr>
      <th>Gremio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @conselho_fiscais.each do |conselho_fiscal| %>
      <tr>
        <td><%= conselho_fiscal.gremio %></td>
        <td><%= link_to 'Show', conselho_fiscal %></td>
        <td><%= link_to 'Edit', edit_conselho_fiscal_path(conselho_fiscal) %></td>
        <td><%= link_to 'Destroy', conselho_fiscal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conselho fiscal', new_conselho_fiscal_path %>

app/views/conselho_fiscais/new.html.erb
<div class="box-info full" >
	<div class="panel">
		<div class="panel-heading">
			<h2 class="text-center">
				<strong> Cadastrando Conselho Fiscal </strong>
			</h2>
			
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/conselho_fiscais/show.html.erb
<div class="bol-xs-12 box-info">
	<div class="panel-heading">
		
		<h2 class="text-center"> <strong> Conselho Fiscal </strong></h2>
		
		<table class="table">
			<thead>				
				<tr>
					<td>
						<div class="form-group">
							<% if policy(@conselho_fiscal).finalizar? %>
								<%= link_to icon('check', 'Finalizar Conselho Fiscal'), finalizar_cadastro_conselho_fiscais_path(@conselho_fiscal), :class => 'btn btn-primary'  %>
							<% end %>
						</div>
						
						<br>
						<br>
						
						<h2>
							Membros (Efetivos)
							<% if policy(@conselho_fiscal).adicionar_membro_efetivo? %>
								<a class="md-trigger btn btn-xs btn-info pull-right" data-modal="consulta-alunos-modal"> <i class="fa fa-plus"></i> Adicionar Membro </a>
							<% end %>
						</h2>
						<% if @conselho_fiscal.membros.exists? %>
							<table class="table table-responsive">
								<thead class="my-table-header">
									<tr>
										<th style="width: 3cm"> Matrícula </th>
										<th> Aluno </th>
										<th> </th>
										<th></th>
									</tr>
								</thead>
								<tbody>
									<% @conselho_fiscal.membros.each do |membro| %>
										<tr>
											<td> <%= membro.aluno.matricula %> </td>
											<td> <a href="<%= membro.aluno %>"> <%= membro.aluno.nome %> </a></td>
											
											<td class="text-right">
												<div class="btn-group btn-group-sm pull-right">
													<% if policy(membro).destroy? %>
									        			| <%= link_to 'Remover', membro, method: :delete, data: { confirm: 'Excluir membro?' } %>
										        	<% end %>
												</div>
											</td>
										</tr>
									<% end %>
								</tbody>
							</table>
						<% else %>
							<h5> Não há membros cadastrados! </h5>
						<% end %>	
					</td>
				</tr>
			</thead>
		</table>
		
		<br>
		<br>
		
		<table class="table table-condensed">
			<thead>
				<tr>
					<td>
						<h2>
							Membros (Suplentes)
							<% if policy(@conselho_fiscal).adicionar_membro_suplente? %>
								<a class="md-trigger btn btn-xs btn-info pull-right" data-modal="consulta-alunos-modal"> <i class="fa fa-plus"></i> Adicionar Membro </a>
							<% end %>
						</h2>
						<% if @conselho_fiscal.membros.exists? %>
							<table class="table table-responsive">
								<thead class="my-table-header">
									<tr>
										<th style="width: 3cm"> Matrícula </th>
										<th> Aluno </th>
										<th> </th>
										<th></th>
									</tr>
								</thead>
								<tbody>
									<% @conselho_fiscal.membros.each do |membro| %>
										<tr>
											<td> <%= membro.aluno.matricula %> </td>
											<td> <a href="<%= membro.aluno %>"> <%= membro.aluno.nome %> </a></td>
											
											<td class="text-right">
												<div class="btn-group btn-group-sm pull-right">
													<% if policy(membro).destroy? %>
									        			| <%= link_to 'Remover', membro, method: :delete, data: { confirm: 'Excluir membro?' } %>
										        	<% end %>
												</div>
											</td>
										</tr>
									<% end %>
								</tbody>
							</table>
						<% else %>
							<h5> Não há membros cadastrados! </h5>
						<% end %>	
					</td>
				</tr>
			</thead>
		</table>	
	</div>
</div>

<%= render 'modal_consulta_alunos_membro_efetivo' %>