config/routes.rb
GremioVirtual::Application.routes.draw do

  devise_for :usuarios,
          path: "",
          controllers: { 
                    sessions: "usuarios/sessions",
                    registrations: "usuarios/registrations",
                    passwords: "usuarios/passwords",
                    password_expired: "usuarios/password_expired"
                  },
                  path_names: { 
                    sign_in: 'entrar',
                    sign_out: 'sair',
                    password: 'senha', 
                    confirmation: 'confirmacao', 
                    unlock: 'desbloquear', 
                    registration: 'perfil', 
                    sign_up: 'sign_up',
                    password_expired: 'senha_expirou'
                }
  
  resources :colegios
  resources :funcionarios
  resources :turmas
  resources :alunos
  
  resources :representante_de_turmas
  
  resources :turmas do
    resources :alunos
    resources :representante_de_turmas, :as => 'representantes', :path => 'representantes'
  end
  
  resources :assembleia_gerais
  
  resources :gremios
  
  resources :chapas
  resources :membro_chapas
  resources :chapas do
    resources :membro_chapas, :as => 'membros'
    collection do
      get 'finalizar_cadastro', :path => '/:id/finalizar_cadastro'
      post 'votar',             :path => '/:id/votar'
    end
  end
  
  resources :eleicao_gremios do
    collection do
      get 'votacao', :path => '/:id/votacao'
    end
  end
  
  resources :cargo_representante_de_turmas
  resources :cargo_funcionarios
  resources :cargo_membro_comissao_eleitorais
  resources :cargo_membro_conselho_fiscais
  
  resources :conselho_fiscais
  resources :conselho_fiscais do
    resources :membro_conselho_fiscais, :as => 'membros', :path => 'membros'
    collection do
      get 'finalizar_cadastro',        :path => '/:id/finalizar_cadastro'
      get 'adicionar_membro_efetivo',  :path => '/:id/adicionar_membro_efetivo/:membro_id'
      get 'adicionar_membro_suplente', :path => '/:id/adicionar_membro_suplente/:membro_id'
    end
  end
  
  resources :conselho_representantes_de_turmas
  resources :conselho_representantes_de_turmas do
    resources :representante_de_turmas, :as => 'representantes', :path => 'representantes'
  end
  
  resources :membro_conselho_fiscais
  resources :comissao_eleitorais do
    resources :membro_comissao_eleitorais, :as => 'membros', :path => 'membros'
    resources :modelo_estatutos
  end
  
  resources :gremios do
    resources :socio_gremios, :as => 'socios', :path => 'socios'
    resources :comissao_eleitorais
    resources :assembleia_gerais
    resources :conselho_representantes_de_turmas
    resources :conselho_fiscais
  end
      
  resources :conselho_fiscais
  resources :conselho_fiscais, :as => :conselho_fiscal do
    resources :membro_conselho_fiscais, :as => 'membros', :path => 'membros'
    collection do
      get 'adicionar_membro_efetivo', :path => '/:conselho_fiscal_id/adicionar_membro_efetivo/:membro_id'
      get 'adicionar_membro_suplente', :path => '/:conselho_fiscal_id/adicionar_membro_suplente/:membro_id'
    end
  end
  
  resources :comissao_pro_gremios
  resources :comissao_pro_gremios do
    resources :membro_comissao_pro_gremios, :as => 'membros', :path => 'membros'
    collection do
      get 'finalizar_cadastro', :path => '/:id/finalizar_cadastro'
      get 'adicionar_membro', :path => '/:id/adicionar_membro/:aluno_id'
    end
  end
  resources :membro_comissao_pro_gremios
  
  
  resources :comissao_eleitorais
  resources :comissao_eleitorais do
    collection do
      get 'finalizar_cadastro', :path => '/:id/finalizar_cadastro'
      get 'adicionar_membro', :path => '/:id/adicionar_membro/:aluno_id'
    end
  end
  
  resources :membro_comissao_eleitorais
  
  
  get 'gremio-estudantil-acoes' => 'gremio_info#acoes', :as => :gremio_estudantil_acoes
  get 'gremio-estudantil-organize-o-na-sua-escola' => 'gremio_info#organize_na_sua_escola', :as => :gremio_estudantil_organize_na_sua_escola
  get 'gremio-estudantil-como-organizar' => 'gremio_info#como_organizar', :as => :gremio_estudantil_como_organizar
  
  root 'gremio_info#acoes'

  
  

end

app/models/cargo_membro_chapa.rb
class CargoMembroChapa < ActiveRecord::Base
  has_many :membro_chapa
  
end

app/controllers/cargo_membro_chapas_controller.rb
# encoding: utf-8

class CargoMembroChapasController < ApplicationController
  before_action :set_cargo_membro_chapa, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  
  def index
    @cargo_membro_chapas = CargoMembroChapa.all
    respond_with(@cargo_membro_chapas)
  end

  def show
    respond_with(@cargo_membro_chapa)
  end

  def new
    @cargo_membro_chapa = CargoMembroChapa.new
    respond_with(@cargo_membro_chapa)
  end

  def edit
  end

  def create
    @cargo_membro_chapa = CargoMembroChapa.new(cargo_membro_chapa_params)
    @cargo_membro_chapa.save
    respond_with(@cargo_membro_chapa)
  end

  def update
    @cargo_membro_chapa.update(cargo_membro_chapa_params)
    respond_with(@cargo_membro_chapa)
  end

  def destroy
    @cargo_membro_chapa.destroy
    respond_with(@cargo_membro_chapa)
  end

  private
    def set_cargo_membro_chapa
      @cargo_membro_chapa = CargoMembroChapa.find(params[:id])
    end

    def cargo_membro_chapa_params
      params.require(:cargo_membro_chapa).permit(:descricao)
    end
end

app/helpers/cargo_membro_chapas_helper.rb
module CargoMembroChapasHelper
end

app/views/cargo_membro_chapas/_form.html.erb
<%= form_for(@cargo_membro_chapa) do |f| %>
  <% if @cargo_membro_chapa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cargo_membro_chapa.errors.count, "error") %> prohibited this cargo_membro_chapa from being saved:</h2>

      <ul>
      <% @cargo_membro_chapa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao, 'Descrição' %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cargo_membro_chapas/edit.html.erb
<div class="box-info full" >
	<div class="panel">
		<div class="panel-heading">
			<h2><strong> Editando Cargo (Membro de Chapa) </strong></h2>
		</div>
		
		<div class="panel-body">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/cargo_membro_chapas/index.html.erb
<h1>Listing cargo_membro_chapas</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cargo_membro_chapas.each do |cargo_membro_chapa| %>
      <tr>
        <td><%= cargo_membro_chapa.descricao %></td>
        <td><%= link_to 'Show', cargo_membro_chapa %></td>
        <td><%= link_to 'Edit', edit_cargo_membro_chapa_path(cargo_membro_chapa) %></td>
        <td><%= link_to 'Destroy', cargo_membro_chapa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cargo membro chapa', new_cargo_membro_chapa_path %>

app/views/cargo_membro_chapas/new.html.erb
<div class="box-info full" >
	<div class="panel">
		<div class="panel-heading">
			<h2><strong> Cadastrando Cargo (Membro de Chapa) </strong></h2>
		</div>
		
		<div class="panel-body">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/cargo_membro_chapas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @cargo_membro_chapa.descricao %>
</p>

<%= link_to 'Edit', edit_cargo_membro_chapa_path(@cargo_membro_chapa) %> |
<%= link_to 'Back', cargo_membro_chapas_path %>